- DspAdpcm/DspAdpcm.Cli/DspAdpcmCli.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmChannel.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmStream.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Dsp.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/IAdpcmStream.cs
- DspAdpcm/DspAdpcm.Encode/DspAdpcm.Encode.csproj
- DspAdpcm/DspAdpcm.Encode/Formats/Dsp.cs
- DspAdpcm/DspAdpcm.Encode/Helpers.cs
- DspAdpcm/DspAdpcm.Encode/Pcm/Formats/Wave.cs
- DspAdpcm/DspAdpcm.Encode/Pcm/IPcmStream.cs
- DspAdpcm/DspAdpcm.Encode/Pcm/PcmChannel.cs
- DspAdpcm/DspAdpcm.Encode/Pcm/PcmStream.cs
- DspAdpcm/DspAdpcm.Uwp/ViewModels/MainViewModel.cs
This will make IAdpcmStream and IAdpcmChannel interfaces and turn the WaveStream class into separate PcmStream and Wave classes
> Make Adpcm interfaces and separate Wave class from PcmStream class

- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmStream.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/DspLR.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/IAdpcmStream.cs
- DspAdpcm/DspAdpcm.Encode/DspAdpcm.Encode.csproj
Adds a simple wrapper for dual-file .dsp streams to the library. Still needs front-end support
> Add support for dual-file .dsp streams

- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmChannel.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmStream.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Dsp.cs
- DspAdpcm/DspAdpcm.Encode/Extensions.cs
- DspAdpcm/DspAdpcm.Encode/Helpers.cs
Adds the ability to read a DSP file into an AdpcmStream
> Add ability to read DSP files

- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmStream.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Brstm.cs
This will add support for reading and writing the HEAD chunk 2 in brstm files. This chunk contains the track data for the brstm file.
> Add support for reading/writing tracks in brstm filesq

- DspAdpcm/DspAdpcm.Uwp/DspAdpcm.Uwp.csproj
- DspAdpcm/DspAdpcm.Uwp/ViewModels/MainViewModel.cs
- DspAdpcm/DspAdpcm.Uwp/Views/Main.xaml
This allows the universal app to read and write dsp and brstm files
> Update UWP app to work with new types

- DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmChannel.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Brstm.cs
- DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Dsp.cs
- DspAdpcm/DspAdpcm.Encode/Extensions.cs
Optimizations for reading and building BRSTM files. Memory copying is a bottleneck here, so reduce that
> File reading/building optimizations

- DspAdpcm/DspAdpcm.Lib/Adpcm/AdpcmChannel.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/AdpcmStream.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Decode.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/B_stm.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/B_stmStructure.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/Bcstm.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/BcstmStructure.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/Brstm.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/BrstmStructure.cs
- DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/DspStructure.cs
- DspAdpcm/DspAdpcm.Lib/BinaryReaderBE.cs
- DspAdpcm/DspAdpcm.Lib/DspAdpcm.Lib.csproj
- DspAdpcm/DspAdpcm.Lib/Extensions.cs
- DspAdpcm/DspAdpcm.Lib/Helpers.cs
- DspAdpcm/DspAdpcm.Uwp/DspAdpcm.Uwp.csproj
- DspAdpcm/DspAdpcm.Uwp/ViewModels/MainViewModel.cs
- DspAdpcm/DspAdpcm.Uwp/Views/Bcstm.xaml
- DspAdpcm/DspAdpcm.Uwp/Views/Bcstm.xaml.cs
- DspAdpcm/DspAdpcm.Uwp/Views/Converters.cs
- DspAdpcm/DspAdpcm.Uwp/Views/Main.xaml
Adds support for reading and writing BCSTM files. Also includes a bit of code cleanup for the Brstm class.
> Add support for BCSTM files

- DspAdpcm/DspAdpcm.Lib/DspAdpcm.Lib.csproj
- DspAdpcm/DspAdpcm.Lib/Pcm/Formats/Wave.cs
- DspAdpcm/DspAdpcm.Lib/Pcm/Formats/WaveStructure.cs
- DspAdpcm/DspAdpcm.Lib/Pcm/PcmChannel.cs
- DspAdpcm/DspAdpcm.Lib/Pcm/PcmStream.cs
Improve reading and writing of WAVE files.
Update the Wave class to match the ADPCM format classes.
> Improve reading and writing of WAVE files.

- DspAdpcm/DspAdpcm/Adpcm/AdpcmChannel.cs
- DspAdpcm/DspAdpcm/Adpcm/Decode.cs
- DspAdpcm/DspAdpcm/Adpcm/Formats/BCFstm.cs
- DspAdpcm/DspAdpcm/Adpcm/Formats/Brstm.cs
- DspAdpcm/DspAdpcm/Adpcm/Formats/Dsp.cs
- DspAdpcm/DspAdpcm/Adpcm/Formats/Idsp.cs
- DspAdpcm/DspAdpcm/Adpcm/Formats/IdspStructure.cs
- DspAdpcm/DspAdpcm/DspAdpcm.csproj
Add support for IDSP files found in SSB4.
> Add support for IDSP files

- DspAdpcm/DspAdpcm/Adpcm/Formats/Genh.cs
- DspAdpcm/DspAdpcm/Adpcm/Formats/Structures/GenhStructure.cs
- DspAdpcm/DspAdpcm/DspAdpcm.csproj
Adds support for reading GENH files using the DSP-ADPCM format
> Add GENH reading

- build/global.json
- src/DspAdpcm.Cli/CliArguments.cs
- src/DspAdpcm.Cli/Convert.cs
- src/DspAdpcm.Cli/DspAdpcm.Cli.csproj
- src/DspAdpcm.Cli/DspAdpcmCli.cs
- src/DspAdpcm.Cli/Options.cs
- src/DspAdpcm/Adpcm/AdpcmStream.cs
- src/DspAdpcm/Pcm/PcmStream.cs
- src/global.json
Add an initial CLI that can:
- Convert between different file types.
- Set loop points.
- Combine multiple inputs.
- Choose specific channels for conversion.
> Add CLI for converting between file types

- build.ps1
- build.sh
- build/Build.csproj
- build/Utilities.cs
- My fix for resolving the Windows 10 SDK was released, so update Cake.
- Update TFM to netcoreapp1.1
> Update build script dependencies

- docs/formats/brstm.bt
- docs/formats/brstm.ksy
- src/VGAudio.Cli/CreateConfiguration.cs
- src/VGAudio.Tests/Containers/BrstmTests.cs
- src/VGAudio.Tests/Containers/WaveTests.cs
- src/VGAudio.Tests/Equality/AudioFormatComparer.cs
- src/VGAudio.Tests/Equality/Pcm8FormatComparer.cs
- src/VGAudio.Tests/GenerateAudio.cs
- src/VGAudio.Uwp/ViewModels/MainViewModel.cs
- src/VGAudio/Codecs/Pcm8Codec.cs
- src/VGAudio/Containers/BrstmReader.cs
- src/VGAudio/Containers/BrstmWriter.cs
- src/VGAudio/Containers/Bxstm/BxstmConfiguration.cs
- src/VGAudio/Containers/Bxstm/Common.cs
- src/VGAudio/Containers/Wave/WaveCodec.cs
- src/VGAudio/Containers/Wave/WaveConfiguration.cs
- src/VGAudio/Containers/Wave/WaveStructure.cs
- src/VGAudio/Containers/WaveReader.cs
- src/VGAudio/Containers/WaveWriter.cs
- src/VGAudio/Formats/Pcm8Format.cs
- src/VGAudio/Formats/Pcm8SignedFormat.cs
- src/VGAudio/Utilities/Extensions.cs
- Read and write 8-bit PCM Wave and BRSTM files
- Add Kaitai Struct format for BRSTM files
> Add 8-bit PCM Wave and BRSTM support

- src/VGAudio.Cli/ContainerTypes.cs
- src/VGAudio.Cli/Convert.cs
- src/VGAudio.Cli/CreateConfiguration.cs
- src/VGAudio.Uwp/ViewModels/MainViewModel.cs
- src/VGAudio/Containers/AudioReader.cs
- src/VGAudio/Containers/AudioWithConfig.cs
- src/VGAudio/Containers/AudioWriter.cs
- src/VGAudio/Containers/BcstmReader.cs
- src/VGAudio/Containers/BfstmReader.cs
- src/VGAudio/Containers/BrstmReader.cs
- src/VGAudio/Containers/Bxstm/BCFstmReader.cs
- src/VGAudio/Containers/Bxstm/BCFstmStructure.cs
- src/VGAudio/Containers/Bxstm/BcstmConfiguration.cs
- src/VGAudio/Containers/Bxstm/BfstmConfiguration.cs
- src/VGAudio/Containers/Bxstm/BrstmConfiguration.cs
- src/VGAudio/Containers/Bxstm/BrstmStructure.cs
- src/VGAudio/Containers/Bxstm/BxstmConfiguration.cs
- src/VGAudio/Containers/Bxstm/BxstmStructure.cs
- src/VGAudio/Containers/Bxstm/Common.cs
- src/VGAudio/Containers/Configuration.cs
- src/VGAudio/Containers/Dsp/DspConfiguration.cs
- src/VGAudio/Containers/Genh/GenhConfiguration.cs
- src/VGAudio/Containers/IAudioWriter.cs
- src/VGAudio/Containers/IConfiguration.cs
- src/VGAudio/Containers/Idsp/IdspConfiguration.cs
- src/VGAudio/Containers/Wave/WaveConfiguration.cs
- Combine BxSTM functions
- Create Configuration abstract class
> Combine common code

- docs/formats/hps.bt
- src/VGAudio.Cli/ContainerTypes.cs
- src/VGAudio.Cli/CreateConfiguration.cs
- src/VGAudio.Cli/Options.cs
- src/VGAudio.Tests/Containers/HpsTests.cs
- src/VGAudio.TestsLong/Common.cs
- src/VGAudio.TestsLong/FileType.cs
- src/VGAudio.Uwp/Audio/ContainerTypes.cs
- src/VGAudio/Containers/Hps/HpsBlock.cs
- src/VGAudio/Containers/Hps/HpsBlockChannel.cs
- src/VGAudio/Containers/Hps/HpsChannelInfo.cs
- src/VGAudio/Containers/Hps/HpsConfiguration.cs
- src/VGAudio/Containers/Hps/HpsStructure.cs
- src/VGAudio/Containers/HpsReader.cs
- src/VGAudio/Containers/HpsWriter.cs
- src/VGAudio/Formats/GcAdpcm/GcAdpcmChannel.cs
- src/VGAudio/Formats/GcAdpcm/GcAdpcmLoopContext.cs
Adds read and write support for HAL Laboratory's HPS audio container.
Implementation is accurate to the HPS files found in Super Smash Bros. Melee, and Kirby Airride
> Add HPS support

- build/Context.cs
- build/LibraryBuildStatus.cs
- build/Lifetime.cs
- build/Tasks/Build.cs
- build/Tasks/BuildReport.cs
- build/Tasks/Meta.cs
- build/Tasks/Package.cs
- build/Tasks/Publish.cs
- build/Tasks/Restore.cs
- build/Tasks/Sign.cs
- src/VGAudio.Tools/GcAdpcm/DspToolDll.cs
- src/VGAudio.Tools/VGAudio.Tools.csproj
- Build VGAudioTools.
- Upload ILRepacked assemblies to AppVeyor.
> Build VGAudioTools in the build script

- build.ps1
- build.sh
- build/Build.csproj
- build/Tasks/Publish.cs
- src/VGAudio.Benchmark/AdpcmBenchmarks/BuildParseBenchmarks.cs
- src/VGAudio.Benchmark/AdpcmBenchmarks/DecodeBenchmarks.cs
- src/VGAudio.Benchmark/AdpcmBenchmarks/EncodeBenchmarks.cs
- src/VGAudio.Benchmark/HelperBenchmarks/BitReaderBenchmarks.cs
- src/VGAudio.Benchmark/HelperBenchmarks/InterleaveBenchmarks.cs
- src/VGAudio.Benchmark/Runner.cs
- src/VGAudio.Benchmark/VGAudio.Benchmark.csproj
- src/VGAudio.Cli/VGAudio.Cli.csproj
- src/VGAudio.Tests/VGAudio.Tests.csproj
- src/VGAudio.Tools/VGAudio.Tools.csproj
- src/VGAudio.Uwp/Package.appxmanifest
- src/VGAudio.Uwp/Properties/AssemblyInfo.cs
- src/VGAudio.Uwp/VGAudio.Uwp.csproj
- src/VGAudio.Uwp/ViewModels/MainViewModel.cs
- src/VGAudio/VGAudio.csproj
- src/global.json
Update VGAudio version and update dependency versions
> Update packages and build process

- src/VGAudio.Cli/Metadata/Containers/Wave.cs
- src/VGAudio/Containers/Wave/WaveReader.cs
- src/VGAudio/Containers/Wave/WaveStructure.cs
- src/VGAudio/Containers/Wave/WaveWriter.cs
- src/VGAudio/Utilities/Riff/MediaSubtypes.cs
- src/VGAudio/Utilities/Riff/RiffChunk.cs
- src/VGAudio/Utilities/Riff/RiffParser.cs
- src/VGAudio/Utilities/Riff/RiffSubchunk.cs
- src/VGAudio/Utilities/Riff/WaveDataChunk.cs
- src/VGAudio/Utilities/Riff/WaveFactChunk.cs
- src/VGAudio/Utilities/Riff/WaveFmtChunk.cs
- src/VGAudio/Utilities/Riff/WaveFormatExtensible.cs
- src/VGAudio/Utilities/Riff/WaveFormatTags.cs
- src/VGAudio/Utilities/Riff/WaveSmplChunk.cs
Adds a generic RIFF parser that can be expanded to handle additional, or extended sub-chunks
> Add a more generic RIFF parser

- src/VGAudio.Tests/VGAudio.Tests.csproj
- src/VGAudio.Uwp/VGAudio.Uwp.csproj
- xUnit
- Microsoft.NETCore.UniversalWindowsPlatform
- PropertyChanged.Fody
> Update NuGet packages

- docs/hca/encryption-keys.md
- src/VGAudio/Codecs/CriHca/CriHcaEncryptionKeys.cs
Added keys for:
- One Piece Treasure Cruise
- Azur Lane
> Add more HCA encryption keys

- src/VGAudio.Cli/Batch.cs
- src/VGAudio.Cli/CliArguments.cs
- src/VGAudio.Cli/ContainerTypes.cs
- src/VGAudio.Cli/Convert.cs
- src/VGAudio.Cli/Converter.cs
- src/VGAudio.Cli/Options.cs
Allows converting multiple files at once
> Add batch conversion to CLI

- build/Lifetime.cs
- src/Directory.Build.props
- src/VGAudio.Uwp/VGAudio.Uwp.csproj
- src/VGAudio/VGAudio.csproj
- Update version to 2.2.0
- Update UWP toolchain
- Update certificate thumbprint
> Update version to 2.2.0

- src/VGAudio/Codecs/CriHca/HcaInfo.cs
- src/VGAudio/Formats/CriHca/CriHcaFormat.cs
- src/VGAudio/Formats/CriHca/CriHcaFormatBuilder.cs
> Allow removing loops from HCA files
