.gitignore
DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Brstm.cs
DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Dsp.cs
DspAdpcm/DspAdpcm.Encode/DspAdpcm.Encode.csproj
DspAdpcm/DspAdpcm.Encode/Extensions.cs
DspAdpcm/DspAdpcm.Encode/Helpers.cs

Add support for BRSTM writing. This code currently uses a lot of LINQ, which for some reason is pretty slow. Need to do some more testing with that.
Instead of the ADPC table being based off the input PCM audio like in BrawlTools' encoder, it's based off of the encoded ADPCM data. This allows for rebuilding of the ADPC table without the original audio.
Currently only the header format found in Super Smash Bros. Brawl is written, but it shouldn't be too hard to add support for other header formats.

BRSTM encoding support

---

DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Brstm.cs
DspAdpcm/DspAdpcm.Encode/Extensions.cs
DspAdpcm/DspAdpcm.Encode/Helpers.cs

Move away from using LINQ in building brstm files. Turns out using LINQ was at least an order of magnitude slower than simply copying arrays around in some cases.

Increase performance of building brstm files

---

DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Brstm.cs
DspAdpcm/DspAdpcm.Encode/Extensions.cs

Add support for reading in data from brstm files and tweak a few things about writing them. Reading and writing brstm files with up to at least 8 channels works.  However, I still don't know what the second chunk in the HEAD section of the file is for, and can't rebuild that part yet on >2-channel brstms.

Add support for reading brstm files

---

DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs

Make output match Nintendo's DSP-ADPCM v2.3 encoder's non-SIMD implementation.  The SIMD implementation varies ever-so-slightly from the non-SIMD implementation. We're talking thousandths of a percent difference when doing a byte-by-byte comparison. Later versions of Nintendo's encoder change the output a bit, so this C# version will stick with v2.3.

Make output match Nintendo's DSP-ADPCM v2.3 encoder's implementation

---

DspAdpcm/DspAdpcm.Encode/Adpcm/AdpcmChannel.cs
DspAdpcm/DspAdpcm.Encode/Adpcm/Encode.cs
DspAdpcm/DspAdpcm.Encode/Adpcm/Formats/Brstm.cs
DspAdpcm/DspAdpcm.Encode/Extensions.cs

This adds the option to use a shortened seek table as used in games including Pokemon Battle Revolution and Mario Party 8.
It also adds the option to not recalculate the seek table when building a file.

Add new options for the ADPCM seek table

---

DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/Brstm.cs
DspAdpcm/DspAdpcm.Lib/Adpcm/Formats/Dsp.cs
DspAdpcm/DspAdpcm.Lib/BinaryWriterBE.cs
DspAdpcm/DspAdpcm.Lib/DspAdpcm.Lib.csproj
DspAdpcm/DspAdpcm.Lib/Extensions.cs

Reading and then writing a file now only does a single whole-file memory allocation instead of 3-4+.
Large increase in speed when reading, converting, and then writing a file. (100%+)

Reduce memory allocations and moving data around in memory when reading and building files

---

src/DspAdpcm/Adpcm/Decode.cs
src/DspAdpcm/Adpcm/Encode.cs
src/DspAdpcm/Adpcm/Formats/Brstm.cs
src/DspAdpcm/Adpcm/Formats/Dsp.cs
src/DspAdpcm/Adpcm/Formats/Genh.cs
src/DspAdpcm/Adpcm/Formats/Idsp.cs
src/DspAdpcm/Adpcm/Formats/Internal/BCFstm.cs
src/DspAdpcm/Adpcm/Formats/Structures/GenhStructure.cs
src/DspAdpcm/BinaryReaderBE.cs
src/DspAdpcm/BinaryWriterBE.cs
src/DspAdpcm/Compatibility/EnumFlag.cs
src/DspAdpcm/Compatibility/Extensions.cs
src/DspAdpcm/Compatibility/Parallel.cs
src/DspAdpcm/Compatibility/Stream.cs
src/DspAdpcm/Compatibility/Tuple.cs
src/DspAdpcm/DspAdpcm.csproj
src/DspAdpcm/Helpers.cs
src/DspAdpcm/Pcm/Formats/Wave.cs
src/DspAdpcm/project.json

Target .NET 4.0, 3.5, and 2.0.
Add backported features as needed.
Add helper functions for getting BinaryReaders and BinaryWriters of the specified endianness.

Add targets for older .NET Framework versions

---

src/VGAudio.Cli/Metadata/Containers/Bfstm.cs
src/VGAudio/Containers/Bxstm/BCFstmReader.cs
src/VGAudio/Containers/Bxstm/BCFstmStructure.cs
src/VGAudio/Containers/Bxstm/RegnChunk.cs

This will read the REGN chunk data from BFSTM files. I've only seen this chunk on BFSTM files, but it should theoretically work on BCSTM files as well.
There are two unknown fields in the REGN chunk. Interestingly enough, the set of values that are found in these fields, and OEIS sequence A029750 through 4096 are equal.

Read REGN chunk data

---

docs/formats/bfstm.bt
docs/formats/brstm.bt
src/VGAudio.Cli/ContainerTypes.cs
src/VGAudio.Cli/Convert.cs
src/VGAudio.Cli/CreateConfiguration.cs
src/VGAudio.Tests/Containers/BcstmTests.cs
src/VGAudio.Tests/Containers/BfstmTests.cs
src/VGAudio/Containers/BcstmReader.cs
src/VGAudio/Containers/BfstmReader.cs
src/VGAudio/Containers/Bxstm/BCFstmReader.cs
src/VGAudio/Containers/Bxstm/BCFstmWriter.cs
src/VGAudio/Containers/Bxstm/BxstmConfiguration.cs
src/VGAudio/Containers/Bxstm/BxstmStructure.cs

Add 8-bit and 16-bit PCM read and write support for both BFSTM and BCSTM files.
Add support for both big-endian and little-endian BFSTM and BCSTM files.

Add PCM support for BFSTM and BCSTM files

---

src/VGAudio.Tests/Helpers/DeinterleaveTests.cs
src/VGAudio.Tests/Helpers/InterleaveTests.cs
src/VGAudio/Utilities/Interleave.cs

The deinterleave and interleave functions would fail when the input was over a block larger than the output. Add tests and fix.
This doesn't usually happen, but BCSTM files tend to contain a little extra audio, and the issue was caught when reading a BCSTM where the extra audio data spilled over into the next interleave block.

Fix deinterleave and interleave bugs

---

src/VGAudio/Codecs/GcAdpcmEncoder.cs

The official implementation does some weird things with floating point types. This will cause slight rounding differences in very rare cases. I found three ADPCM frames that trigger this behavior out of over 5 billion total ADPCM frames.
Now the encoder is 100% accurate to the official implementation, from my testing

Improve ADPCM encoder accuracy

---

docs/formats/bfstm.bt
docs/formats/dsp.bt
src/VGAudio.Benchmark/AdpcmBenchmarks/EncodeBenchmarks.cs
src/VGAudio.Cli/Convert.cs
src/VGAudio.Cli/Metadata/Common.cs
src/VGAudio.Cli/Metadata/Containers/Bxstm.cs
src/VGAudio.Cli/Metadata/Containers/GcAdpcm.cs
src/VGAudio.Cli/Metadata/Containers/Hps.cs
src/VGAudio.Cli/Metadata/Print.cs
src/VGAudio.Tests/Formats/GcAdpcm/GcAdpcmAlignmentTests.cs
src/VGAudio.TestsLong/GcAdpcm/DspToolVGAudio.cs
src/VGAudio/Codecs/GcAdpcmCoefficient.cs
src/VGAudio/Codecs/GcAdpcmDecoder.cs
src/VGAudio/Codecs/GcAdpcmEncoder.cs
src/VGAudio/Containers/Hps/HpsStructure.cs
src/VGAudio/Containers/HpsReader.cs
src/VGAudio/Formats/GcAdpcmFormat.cs
src/VGAudio/Utilities/Helpers.cs

This makes the GC ADPCM encoder and decoder code easier to read, creates a few common helper methods to deal with nibbles, and separates the coefficient calculation into its own class.

Cleanup GC ADPCM encoder

---

src/VGAudio.Cli/CliArguments.cs
src/VGAudio.Cli/CreateConfiguration.cs
src/VGAudio.Cli/Options.cs
src/VGAudio.Tools/CrackAdx/GuessAdx.cs
src/VGAudio/Codecs/CriAdx/CriAdxEncryption.cs
src/VGAudio/Codecs/CriAdx/CriAdxEncryptionKeys.cs
src/VGAudio/Codecs/CriAdx/CriAdxKey.cs
src/VGAudio/Containers/Adx/AdxConfiguration.cs
src/VGAudio/Containers/Adx/AdxReader.cs
src/VGAudio/Containers/Adx/AdxStructure.cs
src/VGAudio/Containers/Adx/AdxWriter.cs
src/VGAudio/Containers/Wave/WaveReader.cs
src/VGAudio/Containers/Wave/WaveWriter.cs

Adds support for reading and writing encrypted ADX files.
Add all ADX keys from VGMStream.
Encryption keys can either be a key string for type 8 encryption, or a key code for type 9 encryption.
Fixed an issue resulting from unaligned WAVE files.

Add encrypted ADX support

---

build.ps1
build.sh
build/Build.csproj
build/Context.cs
build/Tasks/Publish.cs
build/Tools.xml
src/VGAudio.Benchmark/VGAudio.Benchmark.csproj
src/VGAudio.Cli/VGAudio.Cli.csproj
src/VGAudio.Tests/VGAudio.Tests.csproj
src/VGAudio.Tools/VGAudio.Tools.csproj
src/global.json
tools/dotnet/dotnet-install.ps1
tools/dotnet/dotnet-install.sh

- Use .NET Core SDK 2.0
- Target .NET Core 2.0
- Use ILRepack library during build
- Fix issue that placed global.json in the wrong folder during build
- Update dotnet-install scripts

Update to .NET Core 2.0 Runtime and tooling

---

src/VGAudio.Benchmark/Runner.cs
src/VGAudio.Benchmark/UtilityBenchmarks/BitReaderBenchmarks.cs
src/VGAudio.Benchmark/UtilityBenchmarks/InterleaveBenchmarks.cs
src/VGAudio.Tests/Equality/AudioFormatComparer.cs
src/VGAudio.Tests/Formats/GcAdpcm/GcAdpcmAlignmentTests.cs
src/VGAudio.Tests/Formats/GcAdpcmFormatBuilderTests.cs
src/VGAudio.Tests/Utilities/DeinterleaveTests.cs
src/VGAudio.Tests/Utilities/InterleaveTests.cs
src/VGAudio.Tests/Utilities/MdctTests.cs
src/VGAudio.Tests/Utilities/PreBuiltMdctTables.cs
src/VGAudio.Tests/VGAudio.Tests.csproj
src/VGAudio.Tools/Common.cs
src/VGAudio.Tools/FileType.cs
src/VGAudio.Tools/Parse.cs
src/VGAudio.Tools/Rebuild/Rebuilder.cs
src/VGAudio/Utilities/BitReader.cs

- Rename test and benchmark Helpers namespace to Utilities
- Add additional methods to BitReader class
- Rebuilder: If there is no encoder for a format, test that the decode runs without error

Miscellaneous Cleanup

---

build.ps1

HP sets the "Platform" environment variable with some of their software. Clear that variable before building to allow the build to work.

Fix build on HP computers

---

src/VGAudio.Cli/CliArguments.cs
src/VGAudio.Cli/CreateConfiguration.cs
src/VGAudio.Cli/Options.cs

- If the input file is not a WAV file, the default output type will be WAV.
- If the input file is a WAV file, the default output type will be DSP.
- Allow setting the endianness in BCSTM and BFSTM files. (Fixes #74)

Add more options to VGAudioCli

---

src/VGAudio.Cli/Batch.cs

Makes the batch converter run properly on a single-core machine.
Fixes #94

CLI: Fix single core batch processing

---

src/VGAudio/Containers/Hps/HpsWriter.cs

The block size is the size of the data only, not both the data and header

Fix error in HPS loop alignment calculation

---

src/VGAudio.Cli/CliArguments.cs
src/VGAudio.Cli/CreateConfiguration.cs
src/VGAudio.Cli/Options.cs
src/VGAudio/Codecs/Opus/OpusParameters.cs
src/VGAudio/Containers/Opus/NxOpusConfiguration.cs
src/VGAudio/Containers/Opus/NxOpusWriter.cs
src/VGAudio/Formats/Opus/OpusFormat.cs

Before, NxOpusWriter would not write either the frame length field (in the standard header) or the looping bitfield (in the namco header), causing issues with Smash Ultimate, which requires a consistent frame size (as well as a non-zero frame size in the header to accompany it).
My changes consist of:
* Writing the frame length in the header if and only if it is consistent, otherwise the same behavior as before is exhibited
* Writing the looping bit (the 5th least significant) in the bitfield within the NxOpus namco header
To complete support for Smash Ultimate the following change is needed:
* A means of composing equal-sized frames, presumably during encoding(?) in order for these changes to matter

Improve support for Smash Ultimate

---

src/VGAudio.Cli/CliArguments.cs
src/VGAudio.Cli/ContainerTypes.cs
src/VGAudio/Containers/Opus/NxOpusReader.cs
src/VGAudio/Containers/Opus/NxOpusWriter.cs

Those additions aim to add support for the KTSS (OPUS variant) format used in recent Koei Tecmo games.
I reinjected a music converted into the game with success, and the files play properly in Foobar so I'm (somewhat) confident this should be be in a good working state.
Here's proof of it working:
https://twitter.com/Raytwo_ssb/status/1187847995691278344

Implement KTSS format from Fire Emblem Three Houses

---

src/VGAudio.Cli/ContainerTypes.cs

Because in the Japanese version of "3D Classics: Kirby's Adventure"(3Dクラシックス 星のカービィ 夢の泉の物語), BCWAV was used with bms extension
Compiled and converted successfully with Mono. | Monoで正常にコンパイル&変換できました。
OS: Ubuntu 19.10 amd64
```bash
cd VGAudio/src
nuget restore
msbuild
mono ./VGAudio.Cli/bin/Debug/net451/VGAudioCli.exe /media/nnn1590/SDCARD/kriby/bgm/BGM_00_01.bms ~/Music/converted/kirby/BGM_00_01.wav
```
Translated from Japanese to English by Google Translate. | Google 翻訳によって日本語から英語に翻訳されました。

Change to recognize bms extension as BCWAV

---

src/VGAudio/Containers/Wave/WaveWriter.cs

Writing of smpl chunk before data chunk for looping compatibility in NUS3 sound engine.

Write smpl chunk before data chunk
